vimage/models/__init__.py
# -*- coding: utf-8 -*-

from .textset import TextSet
from .imageset import ImageSet, PosterType
from .templet import Templet
from .asset import Asset, Directory
from .sensitive import Sensitive
from .user import User, AnonymousUser

vimage/models/asset.py
# -*- coding: utf-8 -*-
from flask import current_app
from vimage import db, uploader
from vimage.helpers.utils import Dictate, timestamp


__all__ = [
    'Directory',
    'Asset'
]


class Directory(db.Model):
    """Directory of the assets"""

    __tablename__ = 'directories'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), index=True)
    parent_id = db.Column(db.Integer, default=0)
    top = db.Column(db.SmallInteger, default=0)
    type = db.Column(db.SmallInteger, default=1)
    is_default = db.Column(db.Boolean, default=False)

    @property
    def assets(self):
        """某文件夹下文件"""
        return Asset.query.filter_by(directory_id=self.id)

    def to_json(self):
        """资源和JSON的序列化转换"""
        return {
            'rid': self.id,
            'name': self.name,
            'parent_id': self.parent_id,
            'top': self.top,
            'type': self.type,
            'is_default': self.is_default
        }

    def __repr__(self):
        return '<Directory {}>'.format(self.name)


class Asset(db.Model):
    """Asset table.(images、file、video、pdf)"""

    __tablename__ = 'assets'

    id = db.Column(db.Integer, primary_key=True)

    directory_id = db.Column(db.Integer, default=0)

    filepath = db.Column(db.String(128), unique=True, nullable=False)
    filename = db.Column(db.String(255), nullable=False)
    duration = db.Column(db.Float, nullable=True)
    size = db.Column(db.Float, nullable=True)
    width = db.Column(db.Integer, default=0)
    height = db.Column(db.Integer, default=0)
    mime = db.Column(db.String(64), nullable=True)
    # 是否默认图
    is_default = db.Column(db.Boolean, default=False)
    status = db.Column(db.SmallInteger, default=1)

    created_at = db.Column(db.Integer, default=timestamp)
    updated_at = db.Column(db.Integer, default=timestamp, onupdate=timestamp)

    @property
    def view_url(self):
        proto = 'http://'
        if current_app.config['CDN_HTTPS']:
            proto = 'https://'

        if not current_app.config['CDN_DEBUG']:
            url = '{}{}/{}'.format(
                proto,
                current_app.config['THUMB_CDN_DOMAIN'],
                self.filepath) if not self.is_default else '{}'.format(
                self.filepath)
        else:
            url = uploader.url(
                self.filepath) if not self.is_default else '{}'.format(
                self.filepath)

        return url

    @staticmethod
    def host_url():
        proto = 'http://'
        if current_app.config['CDN_HTTPS']:
            proto = 'https://'
        return '{}{}'.format(proto, current_app.config['THUMB_CDN_DOMAIN'])

    @staticmethod
    def default_logo():
        """默认图-Logo"""
        return Dictate({
            'view_url': '%s/static/img/default-logo-180x180.png' % Asset.host_url()
        })

    @staticmethod
    def default_banner():
        """默认图-Banner"""
        return Dictate({
            'view_url': '%s/static/img/default-logo-540x540.png' % Asset.host_url()
        })

    def __repr__(self):
        return '<Asset {}>'.format(self.filepath)

    def to_json(self):
        """资源和JSON的序列化转换"""
        json_asset = {
            'id': self.id,
            'view_url': self.view_url,
            'filepath': self.filepath,
            'filename': self.filename,
            'created_at': self.created_at
        }
        return json_asset

vimage/models/imageset.py
# -*- coding: utf-8 -*-
from sqlalchemy import event
from vimage import db
from vimage.helpers.utils import timestamp, MixGenId
from .asset import Asset

__all__ = [
    'ImageSet',
    'PosterType'
]


class PosterType:
    GOODS_WXA_CODE = 1  # 商品小程序码
    GOODS_PROMOTION_AD = 2  # 商品促销海报


class ImageSet(db.Model):
    """图片及图形库"""

    __tablename__ = 'imagesets'

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, index=True, default=0)
    sn = db.Column(db.String(16), unique=True, nullable=False)

    name = db.Column(db.String(64), nullable=True)
    cover_id = db.Column(db.Integer, default=0)
    description = db.Column(db.Text(), nullable=False)
    tags = db.Column(db.String(200))

    # 1、样例 2、成品图 3、背景 4、矢量图 5、产品图
    type = db.Column(db.SmallInteger, default=1)
    # 是否审核
    approved = db.Column(db.Boolean, default=False)
    # 1、正常（默认）-1：禁用
    status = db.Column(db.SmallInteger, default=1)

    created_at = db.Column(db.Integer, default=timestamp)
    updated_at = db.Column(db.Integer, default=timestamp, onupdate=timestamp)

    @property
    def type_label(self):
        label = ''
        if self.type == 1:
            label = '样例'

        elif self.type == 2:
            label = '成品图'

        elif self.type == 3:
            label = '背景'

        elif self.type == 4:
            label = '矢量图'

        elif self.type == 5:
            label = '产品图'

        return label

    @property
    def cover(self):
        """获取封面图"""
        return Asset.query.get(self.cover_id) if self.cover_id else Asset.default_logo()

    @staticmethod
    def make_unique_sn(sn=None):
        """生成图像编号"""
        if sn is None:
            sn = MixGenId.gen_image_sn()

        if ImageSet.query.filter_by(sn=sn).first() is None:
            return sn

        while True:
            new_sn = MixGenId.gen_image_sn()
            if ImageSet.query.filter_by(sn=new_sn).first() is None:
                break
        return new_sn

    @staticmethod
    def on_before_insert(mapper, connection, target):
        # 自动生成编号
        if target.sn:  # 存在，验证是否唯一
            target.sn = ImageSet.make_unique_sn(target.serial_no)
        else:
            target.sn = ImageSet.make_unique_sn()

    def to_json(self):
        """对象转换"""
        json = {
            "status": self.status,
            "created_at": self.created_at,
            "updated_at": self.updated_at
        }

        return json

    def __repr__(self):
        return '<ImageSet {}>'.format(self.sn)


# 监听事件
event.listen(ImageSet, 'before_insert', ImageSet.on_before_insert)

vimage/models/sensitive.py
# -*- coding: utf-8 -*-
from vimage import db


__all__ = [
    'Sensitive'
]


class Sensitive(db.Model):
    """广告违禁词及敏感词库"""

    __tablename__ = 'sensitives'

    id = db.Column(db.Integer, primary_key=True)
    word = db.Column(db.String(32), nullable=False)
    # 类型：1、广告违禁词；2、敏感词；
    type = db.Column(db.SmallInteger, default=1)

    @property
    def type_label(self):
        label = ''
        if self.type == 1:
            label = '广告违禁词'

        elif self.type == 2:
            label = '敏感词'

        return label

    def __repr__(self):
        return '<Sensitive {}>'.format(self.word)

vimage/models/templet.py
# -*- coding: utf-8 -*-
from sqlalchemy import event
from vimage import db
from vimage.helpers.utils import timestamp, MixGenId
from .asset import Asset


__all__ = [
    'Templet'
]


class Templet(db.Model):
    """模板库"""

    __tablename__ = 'templets'

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, index=True, default=0)

    sn = db.Column(db.String(16), unique=True, nullable=False)
    name = db.Column(db.String(64), nullable=False)
    cover_id = db.Column(db.Integer, default=0)
    # 模板类型，1、商品小程序码
    type = db.Column(db.SmallInteger, default=1)
    # 使用次数
    use_times = db.Column(db.Integer, default=0)
    # 说明要求
    requirements = db.Column(db.Text(), nullable=True)
    # 1、正常（默认）-1：禁用
    status = db.Column(db.SmallInteger, default=1)

    created_at = db.Column(db.Integer, default=timestamp)
    updated_at = db.Column(db.Integer, default=timestamp, onupdate=timestamp)

    @property
    def type_label(self):
        label = ''
        if self.type == 1:
            label = '小程序商品推广图'

        return label

    @property
    def cover(self):
        """获取封面图"""
        return Asset.query.get(self.cover_id) if self.cover_id else Asset.default_logo()

    @staticmethod
    def make_unique_sn(sn=None):
        """生成模板编号"""
        if sn is None:
            sn = MixGenId.gen_templet_sn()

        if Templet.query.filter_by(sn=sn).first() is None:
            return sn

        while True:
            new_sn = MixGenId.gen_templet_sn()
            if Templet.query.filter_by(sn=new_sn).first() is None:
                break
        return new_sn

    @staticmethod
    def on_before_insert(mapper, connection, target):
        # 自动生成编号
        if target.sn:  # 存在，验证是否唯一
            target.sn = Templet.make_unique_sn(target.serial_no)
        else:
            target.sn = Templet.make_unique_sn()

    def to_json(self):
        """对象转换"""
        json_obj = {
            'sn': self.sn,
            'name': self.name,
            'cover': self.cover.view_url,
            'type': self.type,
            'requirements': self.requirements,
            'status': self.status
        }

        return json_obj

    def __repr__(self):
        return '<Templet {}>'.format(self.sn)


# 监听事件
event.listen(Templet, 'before_insert', Templet.on_before_insert)

vimage/models/textset.py
# -*- coding: utf-8 -*-
from vimage import db
from vimage.helpers.utils import timestamp


__all__ = [
    'TextSet'
]


class TextSet(db.Model):
    """文本语料库"""

    __tablename__ = 'textsets'

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, index=True, default=0)
    content = db.Column(db.Text(), nullable=False)
    tags = db.Column(db.String(200))
    # 1、单句 2、片段 3、广告语
    type = db.Column(db.SmallInteger, default=1)
    # 是否审核
    approved = db.Column(db.Boolean, default=False)
    # 1、正常（默认）-1：禁用
    status = db.Column(db.SmallInteger, default=1)

    created_at = db.Column(db.Integer, default=timestamp)
    updated_at = db.Column(db.Integer, default=timestamp, onupdate=timestamp)

    def __repr__(self):
        return '<TextSet {}>'.format(self.id)

vimage/forms/__init__.py
# -*- coding: utf-8 -*-

from .templets_forms import TempletForm
from .sensitive_words_forms import SensitiveWordsForm
from .images_forms import ImagesForm

vimage/forms/images_forms.py
# -*- coding: utf-8 -*-
from flask_wtf import FlaskForm as Form
from wtforms import StringField, TextAreaField, IntegerField, FloatField, SelectField, RadioField, BooleanField, FileField
from wtforms.validators import DataRequired, InputRequired, Length, ValidationError, optional


class ImagesForm(Form):
    image = FileField('选择图像')
    name = StringField('图像名称')
    tags = StringField('标签', validators=[Length(1, 200)])
    description = TextAreaField('图像描述', validators=[DataRequired(message='描述不能为空'), Length(2, 64)])
    cover_id = IntegerField('封面图', default=0)
    type = SelectField('图像类型', choices=[(1, '样例'), (2, '成品图'), (3, '背景'), (4, '矢量图'), (5, '产品图')],
                       coerce=int, default=1)
    approved = BooleanField('是否审核', false_values=False)
    status = RadioField('状态', choices=[(1, '可用'), (-1, '禁用')], coerce=int, default=1)

vimage/forms/sensitive_words_forms.py
# -*- coding: utf-8 -*-
from flask_wtf import FlaskForm as Form
from wtforms import StringField, TextAreaField, IntegerField, FloatField, SelectField, RadioField
from wtforms.validators import DataRequired, InputRequired, Length, ValidationError, optional


class SensitiveWordsForm(Form):
    word = StringField('文字内容', validators=[DataRequired(message='内容不能为空'), Length(1, 128)])
    type = SelectField('文字类型', choices=[(1, '广告违禁词'), (2, '敏感词')], coerce=int, default=1)

vimage/forms/templets_forms.py
# -*- coding: utf-8 -*-
from flask_wtf import FlaskForm as Form
from wtforms import StringField, TextAreaField, IntegerField, FloatField, SelectField, RadioField
from wtforms.validators import DataRequired, InputRequired, Length, ValidationError, optional


class TempletForm(Form):
    name = StringField('模板名称', validators=[DataRequired(message='模板名称不能为空'), Length(2, 64)])
    cover_id = IntegerField('模板图', default=0)
    type = SelectField('模板类型', choices=[(1, '商品推广码')], coerce=int, default=1)
    requirements = TextAreaField('模板要求')
    status = RadioField('状态', choices=[(1, '可用'), (-1, '禁用')], coerce=int, default=1)

vimage/__init__.py
# -*- coding: utf-8 -*-
"""
    __init__.py
    ~~~~~~~~~~~~~~
    :copyright: (c) 2018 by purpen.
"""
import os
from flask import Flask
# 导入扩展
from .extensions import (
    db,
    csrf,
    cache,
    cdn,
    fsk_celery,
    bootstrap,
    login_manager
)
# 导入上传
from flask_uploads import UploadSet, configure_uploads, patch_request_class
from .assets import assets_env, bundles
# 导入配置参数
from config import config

basedir = os.path.abspath(os.path.dirname(__file__))

# 创建set
uploader = UploadSet(
    'photos',
    extensions=('xls', 'xlsx', 'jpg', 'jpe', 'jpeg', 'png', 'gif', 'csv')
)
# 属性可以设为None、'basic' 或'strong'
login_manager.session_protection = 'strong'
# 设置登录页面的端点
login_manager.login_view = 'auth.login'


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])

    # 加载私有环境变量
    if os.path.exists('%s/private_config.py' % basedir):
        app.config.from_pyfile('%s/private_config.py' % basedir)

    config[config_name].init_app(app)
    
    db.init_app(app)
    bootstrap.init_app(app)
    login_manager.init_app(app)
    csrf.init_app(app)

    assets_env.init_app(app)
    assets_env.register(bundles)
    # cdn
    cdn.init_app(app)
    # 缓存
    cache.init_app(app)

    # Init the Flask-Celery-Helper via app object
    # Register the celery object into app object
    fsk_celery.init_app(app)

    # 初始化上传
    configure_uploads(app, uploader)
    # 文件大小限制，默认为16MB
    patch_request_class(app)

    # logging setting
    if not app.debug:
        import logging
        from logging.handlers import RotatingFileHandler
        file_handler = RotatingFileHandler(app.config['ERROR_LOG'])
        file_handler.setLevel(logging.DEBUG)
        file_handler.setFormatter(logging.Formatter(
            '%(asctime)s %(levelname)s: %(message)s [in %(pathname)s:%(lineno)d]'))
        app.logger.addHandler(file_handler)
        app.logger.setLevel(logging.DEBUG)
        app.logger.info('Mix startup')

    # attach routes

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .adminlte import adminlte as adminlte_blueprint
    app.register_blueprint(adminlte_blueprint, url_prefix='/adminlte')

    from .api_1_0 import api as api_1_0_blueprint
    app.register_blueprint(api_1_0_blueprint, url_prefix='/api/v1.0')
    # 禁用csrf
    csrf.exempt(api_1_0_blueprint)

    return app

vimage/adminlte/__init__.py
# -*- coding: utf-8 -*-

from flask import Blueprint

adminlte = Blueprint('adminlte', __name__)

from . import views, templet, file_manager, sensitive_words, images

vimage/adminlte/views.py
# -*- coding: utf-8 -*-
from flask import render_template

from . import adminlte


@adminlte.route('/')
def dashboard():
    """管理控制台"""
    features = [
        '智能海报生成', '智能Banner生成', '社交图文生成', '图片添加二维码', '广告违禁词识别', '一键生成主图短视频', '智能图像压缩', '以图搜图比价',
        '图像识别商品标注', '图片情感分析', '智能生成PPT', 'GIF动图制作'
    ]
    return render_template('adminlte/dashboard.html',
                           features=features)

vimage/api_1_0/__init__.py
# -*- coding: utf-8 -*-
from flask import Blueprint
from flask_cors import CORS

api = Blueprint('api', __name__)

# 存在跨域的问题
CORS(api)

from . import views, maker, tools, templet

vimage/api_1_0/views.py
# -*- coding: utf-8 -*-
"""
    views.py

    :copyright: (c) 2018 by purpen.
"""
from flask import request, abort, g, url_for, jsonify

from . import api
from vimage.helpers.utils import *
from vimage.helpers.poster_make import *
from vimage.models import ImageSet
from vimage.models.sensitive import *
from vimage import db


@api.route('/', methods=['GET'])
def hello_world():
    """test"""

    return 'Hello World!'

vimage/helpers/__init__.py
# -*- coding: utf-8 -*-
from .poster_make import TextObject, ImageObject, Poster
from .qiniu_cloud import QiniuCloud, QiniuError
from .gif_make import GifTool
from .sensitive import PickSensitive
from .video_make import VideoMake
from .qr_code_make import QRCodeObject

vimage/main/__init__.py
# -*- coding: utf-8 -*-

from flask import Blueprint

main = Blueprint('mainImage', __name__)

from . import views

vimage/main/views.py
# -*- coding: utf-8 -*-
from . import main


@main.route('/')
def index():
    """欢迎页"""
    return 'Hello, Moebeast!'

vimage/templates/layout/admin.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta http-equiv="Access-Control-Allow-Origin" content="*">
		<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
		<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
		<title>moebeast - 智能图像服务商</title>

		<style type="text/css">
			@font-face {
				font-family: 'FontAwesome';
			    src: url('/static/fonts/fontawesome-webfont.eot?v=4.7.0');
			    src: url('/static/fonts/fontawesome-webfont.eot?#iefix&v=4.7.0') format('embedded-opentype'), url('/static/fonts/fontawesome-webfont.woff2?v=4.7.0') format('woff2'), url('/static/fonts/fontawesome-webfont.woff?v=4.7.0') format('woff'), url('/static/fonts/fontawesome-webfont.ttf?v=4.7.0') format('truetype'), url('/static/fonts/fontawesome-webfont.svg?v=4.7.0#fontawesomeregular') format('svg');
			    font-weight: normal;
			    font-style: normal;
			}
			@font-face {
				font-family: 'Glyphicons Halflings';
				src: url('/static/fonts/glyphicons-halflings-regular.eot');
				src: url('/static/fonts/glyphicons-halflings-regular.eot?#iefix') format('embedded-opentype'), url('/static/fonts/glyphicons-halflings-regular.woff2') format('woff2'), url('/static/fonts/glyphicons-halflings-regular.woff') format('woff'), url('/static/fonts/glyphicons-halflings-regular.ttf') format('truetype'), url('/static/fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular') format('svg');
			}
		</style>

		{% assets "admin_css" %}
		<link href="{{ ASSET_URL }}" type="text/css"  rel="stylesheet">
  		{% endassets %}

		{% block private_styles %}{% endblock %}

		{% assets "app_css" %}
		<link href="{{ ASSET_URL }}" type="text/css" rel="stylesheet">
  		{% endassets %}

		{% assets "themes_css" %}
		<link href="{{ ASSET_URL }}" type="text/css" rel="stylesheet">
  		{% endassets %}

		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->
	</head>

	<body class="adminlte skin-green-light">
		{% block header %}
		<header class="main-header navbar-fixed-top">
			<a class="logo" href="{{ url_for('adminlte.dashboard') }}">
				vimage
			</a>
			<nav class="navbar navbar-static-top">
				<ul class="nav navbar-nav navbar-menu">
					<li {% if top_menu == 'images' %}class="active"{% endif %}>
						<a href="{{ url_for('adminlte.get_images') }}">图像</a>
					</li>
					<li {% if top_menu == 'templets' %}class="active"{% endif %}>
						<a href="{{ url_for('adminlte.get_templets') }}">模板</a>
					</li>
					<li {% if top_menu == 'sensitive_words' %}class="active"{% endif %}>
						<a href="{{ url_for('adminlte.get_sensitive_words') }}">敏感词</a>
					</li>
				</ul>
				<div class="navbar-custom-menu">
					<ul class="nav navbar-nav">
						<li class="dropdown user user-menu">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
								<img src="/static/img/avatar.png" class="user-image" alt="User Image">
								<span class="hidden-xs">
									{% if current_user.is_authenticated %}
										{{ current_user.username }}
									{% endif %}
								</span>
							</a>

							<ul class="dropdown-menu">
								<li class="header">
									快捷链接
								</li>
								<li>
									<a href="">偏好设置</a>
								</li>
								<li role="separator" class="divider"></li>
								<li>
									<a href="">安全退出</a>
								</li>
							</ul>
						</li>
		                <li>
		                    <a href="#" data-toggle="control-sidebar">
		                        <i class="fa fa-question-circle-o"></i>
		                    </a>
		                </li>
					</ul>
				</div>
			</nav>
		</header>
		{% endblock %}

		<div class="container-fluid">
			{% block content %}
			<div class="col-sm-3 col-md-2 sidebar">
				{% block sidebar %}{% endblock %}
			</div>
			<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main" id="pjax-container">
				{% with messages = get_flashed_messages(with_categories=true) %}
					{% if messages %}
					<div class="flashes">
						{% for category, message in messages %}
						<div class="alert alert-{{ category }} alert-dismissable">
							<button class="close" type="button" data-dismiss="alert" aria-hidden="true">×</button>
							{% if category == 'success' %}
							<strong>Well done!</strong>
							{% endif %}

							{% if category == 'danger' %}
							<strong>Oh snap!</strong>
							{% endif %}

							{{ message }}
						</div>
						{% endfor %}
					</div>
					{% endif %}
				{% endwith %}

				{% block mainbar %}{% endblock %}
			</div>
			{% endblock %}
		</div> <!-- /container -->

		{% block footer %}{% endblock %}
		<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
		{% assets "admin_js" %}
  		<script type="text/javascript" src="{{ ASSET_URL }}"></script>
  		{% endassets %}

		{% assets "app_js" %}
  		<script type="text/javascript" src="{{ ASSET_URL }}"></script>
  		{% endassets %}

		<script type="text/javascript">
			// 加载js执行前的配置信息
			mixpus.csrf_token = "{{ csrf_token() }}";
			mixpus.locale = {
				selected_label: "个项被选中"
			};
			
			mixpus.urls = {
				show_assets: '{{ url_for("adminlte.show_asset") }}'
			};

			// 打开页面时加载进度条。
			NProgress.start();

			$(function(){
				NProgress.done();

				{% block jquery %}
				// current document scripts
				{% endblock %}
			});
		</script>

		{% block private_js %}{% endblock %}
		{% block after_jquery %}
		<script type="text/javascript">
			$(function () {
				mixpus.init_page_layout();
			});
		</script>
		{% endblock %}

	</body>
</html>